### ISSUE TITLE
Hitting the root URL results in an error

### ISSUE THREAD

**Issue by hferentschik** [redhat-helloworld-msa/helloworld-msa#1]
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Apr 21 03:48:34 UTC 2016
There was an unexpected error (type=Not Found, status=404).
No message available
```

**Comment by hferentschik** [comment]
Ahh, that was supposed to be for one of the other micro-services. Created the issue in the wrong repo.

**Comment by rafabene** [comment]
Anyway I was thinking that all microservices should have an index page listing the current endpoints. I was wondering about using swagger to document those endpoints. I just opened a discussion about that with @burrsutter @christian-posta and @yanaga

**Comment by hferentschik** [comment]
> Anyway I was thinking that all microservices should have an index page listing the current endpoints.

What's under the root URL is debatable, but it need to be something. Easiest is the redirect. But having an index page with maybe some static content giving some additional help and information is probably a good ideas as well. In this case there should definitely also be a link to the service endpoint. 

As a user and when doing the demo, I want to be able to navigate from the console via the visible exposed route. Having a 503 or other similar errors coming up is just confusing.

**Comment by rafabene** [comment]
👍

**Comment by rafabene** [comment]
All services has and a default page that points to a swagger instance running in the frontend.

**Comment by hferentschik** [comment]
Awesome, thanks
