### ISSUE TITLE
ansible script to deploy helloworld-msa to a regular OpenShift 3.2 cluster (not CDK)

### ISSUE THREAD

**Issue by wrichter** [redhat-helloworld-msa/helloworld-msa#13]
for a demo we're building we've stood up a (shared) OpenShift cluster. To deploy helloworld-msa to it, we've built the folllowing ansible script: https://github.com/wrichter/hailstorm/tree/master/ansible/roles/layerX_openshift_demo_redhatmsa_on_devclient/tasks

This role is applied to  a RHEL system with software collections providing maven and nodejs which connects to the openshift cluster. This system has all the preregs (bzip2,git,bash-completion,atomic-openshift-clients,java-1.8.0-openjdk-devel,rh-maven33,rh-nodejs4) installed via yum and has two OS users called "developer" and "admin". On the Openshift cluster, the admin user has cluster-admin permissions.

This script is almost idempotent and can be run multiple times without failing. 

Since we never forked from this repo, I cannot send a pull request :-( but maybe it's still good for inspiration.

**Comment by rafabene** [comment]
It seems that it does the same thing of this ansible script but using different approaches. Am I right? https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/ansible/helloworld-msa.yml

**Comment by wrichter** [comment]
a little bit less (doesn't deploy jenkins), more focus on idempotency, doesn't modify cluster-wide things such as the restricted scc

**Comment by rafabene** [comment]
Given the status of the current Ansible script, we will keep using the current version.
