### ISSUE TITLE
Unable to find RHEL image on Red Hat Customer Portal

### ISSUE THREAD

**Issue by metmajer** [redhat-helloworld-msa/helloworld-msa#16]
The documentation proposes to use the demo application with the CDK. When visiting the Red Hat Customer Portal link provided in the README, I only see a CD and DVD download, but no Vagrant or whatsoever image.

**Comment by metmajer** [comment]
Not sure, but maybe the link should be updated? The reason I did not see the download under the proposed link was because I wasn't logged in as a Red Hat Developers program member. Here I found a link which gives an overview about the most recent version and only denies access if not logged in properly: http://developers.redhat.com/products/cdk/download/

**Comment by rafabene** [comment]
Thanks @metmajer for the feedback
