### ISSUE TITLE
Auto discover ZipKin/OpenTracing/APM server URL

### ISSUE THREAD

**Issue by jpkrohling** [redhat-helloworld-msa/helloworld-msa#22]
Change the ZipKin service name to a generic one, and make the examples discover it, either by consuming the env vars or by doing a DNS lookup. 

Env vars:
```
SVC_NAME_SERVICE_ADDRESS is the service IP address.
SVC_NAME_SERVICE_PORT is the service TCP port.
```

DNS lookup:
```
SVC_NAME.PROJECT_NAME.svc.cluster.local
```

Where `SVC_NAME` is the service name.

**Comment by rafabene** [comment]
Actually all services uses http://zipkin:9441/ as internal address.
