### ISSUE TITLE
Add a unique label per service

### ISSUE THREAD

**Issue by hferentschik** [redhat-helloworld-msa/helloworld-msa#4]
At the moment most services add the label '-l hystrix.enabled=true' to be able to select resources with hystrix enabled. However, each service should also define its own specific label (in the setup command), something like 'ola-service', 'helllo-service', ...

This way one can easily act upon all resources belonging to a single service. In particular one can delete all resources for a given service `oc delete all -l hola-service`.

Given that all components of the application end up in the same project it is essential that there is a easy way to address just the resources of a single component. AFAIK, the only way to do this in Kubernates/OpenShift are labels.

**Comment by rafabene** [comment]
It actually sets some labels additionally to hystrix.enabled. Examples:
app=frontend, app=bonjour, project=ola, project=hello, etc.

I use "oc delete all -l <label>" a lot. So I know that this works.

**Comment by rafabene** [comment]
Reopening this since some services don't create labels. It could be an issue with the s2i image. Example: aloha and vert.x s2i builder

**Comment by rafabene** [comment]
Thanks for your reports @hferentschik

**Comment by hferentschik** [comment]
> Thanks for your reports

No. Great demo app :-)
