### ISSUE TITLE
Error: image jboss-eap-7-beta/eap70-openshift:1.3 not found

### ISSUE THREAD

**Issue by iocanel** [redhat-helloworld-msa/helloworld-msa#5]
I am trying to build `hello` using Option 1 (with docker fabric8 maven plugin) and I am hitting this issue.

**Comment by rafabene** [comment]
You just missed the issue :)

**Comment by rafabene** [comment]
Ah! I found the issue in the $subject. I'll try to reproduce. Thanks

**Comment by rafabene** [comment]
That image still available. Please check if your Docker daemon is pointing to CDK docker daemon (that has registry.access.redhat.com set). To use CDK internal docker daemon, run: eval "$(vagrant service-manager env docker)" at the same folder of the Vagrantfile.

**Comment by iocanel** [comment]
I was using the fabric8 vagrant stuff and I don't have configured registry.access.redhat.com.

Thanks!

**Comment by rafabene** [comment]
👍

**Comment by iocanel** [comment]
I also got this example working with `jboss/wildfly`. Would a PR interest you or you'd rather keep it using `eap` ?

**Comment by rafabene** [comment]
Initially we used `jboss/wildfly`, but since we are focusing on the product we decided to move to `eap`. Maybe we can just drop a WILDFLY.md explaining the needed changes (pom.xml and Dockerfile) to run it on WildFly.

**Comment by iocanel** [comment]
Makes sense to me.

What do you think of maven profile for WF?

**Comment by rafabene** [comment]
Even better. :)

On Mon, May 16, 2016 at 10:37 AM, Ioannis Canellos <notifications@github.com

> wrote:
> 
> Makes sense to me.
> 
> What do you think of maven profile for WF?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/redhat-helloworld-msa/helloworld-msa/issues/5#issuecomment-219441658

## 

_Rafael Benevides | Senior Product Manager_
Director of Developer Experience
M: +1-919-592-6255

Better technology. Faster innovation. Powered by community collaboration.
See how it works at www.redhat.com
